class Data {
  static final getData = [
    {
      'name': 'Shaked',
      'description': 'Smoothie bowl',
      'image': 'Images/shaked.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '20',
      'likes': '400',
    },
    {
      'name': 'Noa',
      'description': 'Smoothie bowl',
      'image': 'Images/noa.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '12',
      'likes': '503',
    },
    {
      'name': 'Wanted l very very very vey veyu',
      'description': 'Smoothie bowl very very very vey veyu veryu',
      'image': 'Images/wanted.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
      '_isFavorited': 'false'
    },
    {
      'name': 'Danielle very very very very',
      'description': 'Smoothie bowl',
      'image': 'Images/danielle.jpg',
      'author': 'danielle',
      'hours': '0',
      'minutes': '30',
      'likes': '2',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pizza.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pizza.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pizza.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pizza.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pestopasta.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/ruz.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pestopasta.jpg',
      'author': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
  ];
}
