import 'package:flutter/material.dart';

class Data {
  static final getData = [
    {
      'name': 'Shaked',
      'description': 'Smoothie bowl',
      'image': 'Images/shaked.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '20',
      'likes': '400',
    },
    {
      'name': 'Noa',
      'description': 'Smoothie bowl',
      'image': 'Images/noa.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '12',
      'likes': '503',
    },
    {
      'name': 'Wanted ',
      'description': 'Smoothie bowl',
      'image': 'Images/wanted.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Danielle',
      'description': 'Smoothie bowl',
      'image': 'Images/danielle.jpg',
      'athor': 'danielle',
      'hours': '0',
      'minutes': '30',
      'likes': '2',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pizza.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pizza.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pizza.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pizza.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pestopasta.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/ruz.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
    {
      'name': 'Pasta',
      'description': 'pasta with pesto',
      'image': 'Images/pestopasta.jpg',
      'athor': 'danielle',
      'hours': '1',
      'minutes': '0',
      'likes': '7',
    },
  ];
}
